language: node_js
node_js:
  - 6.10.2
sudo: required
services:
  - docker
env:
  - CXX=g++-4.8 PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1
addons:
  sauce_connect:
    username: princu7
  jwt:
    secure: LN+IXY8CWRMWIrDTTi1s6oa8YsnwvzPOq5MVB9kBPvqgSIVszDGdyJH3NeJhOC77LPF+xs7LGSxKy9vhybQ/46Xm6B2Tex1+RnWWYDdIV1IWATWpLxWJgoPanPp/HZUQMa8djNwH8ejaN4dVg3/1Wb+i7OH1IGlPg2WEaR1T07o6+kKCxPB58UjtEz4rT8nGB5wtTfHhMdY4UsHXmYD4ZedlpYQo8pLYNgY4Woz8UAcFNnrerQcJmjXp/yYzfFAgKuyCZOH/9sTfGKAXMHHydOrKvDDHbfuxdGxX/XNiG4KggN8JzEBO4vp/vi/uJn4J7xLNLTa+kPLYiG8KprrFBa5B1rabpnCWNYyil7Cd43KwPYEOWgzhKbUZVwcfEL4g2HrpY/q5NV43E9nUfcgmsE+wIZ6YYzrhwN2GPdqhSdop9vHxxmVrhYXLXM02NuRaaZjSpya+kGTEJi36LjjQ7WZH3M9WrHpVVCdm1JCfGT4l84Tk3oeFxo3wolt34OwPSVJpClsQ2ds2on/jxv/zIagv53sXAOya2emReuO+/sh7wgcmOXMl94oxj7QFw/CNQBZpa4C91LgqBjxN7frpE2mkGDSXWOl3vtF0+asolSon9CkGwUUPgmQkM85lSyZ7Yd+rDrSwqztXkrHIWB9CrJREhn4bHn2xyGWR3M25GO0=
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  code_climate:
    repo_token: 46f6d31d6b0777711b6c7e733234b023bda56e2e02c792c68c889005cf032ea6
install:
  - npm install -g istanbul mocha
  - npm install
script:
  - istanbul cover _mocha
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash cli.sh
  - bash sample_cli.sh
  - bash gh_deploy.sh
  - bash kubernetes/travis/deploy.sh
deploy:
  provider: heroku
  api_key:
    secure: ogAnS9LCFXVkMocd7DbYup45n8eRHIFpeptDP947PajNy27xPfOspBGj1UMQri/0d/hAYqdC52Bfd7eccyOLm/6H9d5LzDWNBHz4rqT+FXkdpJf7PofC7kUua5oUXlh0eiccBKwn3j8n3suLnLsigJ/UD4rjKIGKrfodAud4XhsPdg0+XVNihDa6rSMH5G6TTAYQjukCLT2TlCPFiyNSJvfjH1+h2uE93vWBzsjkLzlWMoAr00uAwlYJgotoQ9v2ECqfZ7mhAJCwSoRdqmir9Xvj5GSj3qRc953bbye8ZJoEMXDt9N2GNwV3/3XFtrc/fQuq7cRj2OFZuDZ/Ch0Z2MQGbXoG0gqRfntoGFBDcx4w+rifburPnIDS4V4H5DpW/lohGG6tWLSa4ynfF5utnUowpy9pT8RCBmrvZkLfSfqF4J/rh7HzfyhMpDGqv5hcs+RSJZQiLN8sdcSRvz2aKoaAxXi7U0IfUAUluJ9fPD5WRmUbV3FwAxEjjuRMKYabelam7lvKI6vyf6lWt1oyI4EKd7M33JfeRbcJ9BwM4SDbgxHCSeSI4AIiqFs1l35ZVfDlz8yLhHt33ZWSBrWoGw3e83rUJPc/I9Uxu4xX3WKCZ+tXKD8YA64rdeoCDra/2Ad2Rm4doFgdWmW2I23jKNx/CtKiq3YXcWmiBCaL6IQ=
  app: opev-webgen-dev
  on:
    repo: fossasia/open-event-webapp
    branch:
      - master
      - development
